#name: Create Release
#on:
#  push:
#    # Sequence of patterns matched against refs/tags
#    tags:
#      - 'v*' # Push events to matching v*, i.e. v1.0, v0.4.4
#
#jobs:
#  test:
#    runs-on: ubuntu-18.04
#    steps:
#      # To use this repository's private action, you must check out the repository
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Generate changelog
#        id: changelog
#        uses: jaywcjlove/changelog-generator@v1.3.9
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          filter-author: (jaywcjlove|小弟调调™|dependabot\[bot\]|Renovate Bot)
#          filter: (^[\s]+?[R|r]elease)|(^[R|r]elease)
#
#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@latest
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: ${{ github.ref }}
#          body: |
#            ${{ steps.changelog.outputs.compareurl }}
#            ${{ steps.changelog.outputs.changelog }}
#          draft: false
#          prerelease: false
